version: "3"
services:
  # airflow:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.airflow
  #   image: airflowimage
  #   container_name: gemstone-prediction-airflow
  #   ports:
  #     - "8080:8080"
    
  flaskapp:
    build:
      context: ./
      dockerfile: Dockerfile.flask
    image: flaskimage
    container_name: adult_census_salary_prediction
    ports:
      - "80:80"
    